/*
 * Auto-Generated File. Changes will be destroyed.
 */
#include "squid.h"
#include "LogTags.h"

const char * LogTags_str[] = {
	"TAG_NONE",
	"TCP_HIT",
	"TCP_MISS",
	"TCP_REFRESH_UNMODIFIED",
	"TCP_REFRESH_FAIL_OLD",
	"TCP_REFRESH_FAIL_ERR",
	"TCP_REFRESH_MODIFIED",
	"TCP_CLIENT_REFRESH_MISS",
	"TCP_IMS_HIT",
	"TCP_SWAPFAIL_MISS",
	"TCP_NEGATIVE_HIT",
	"TCP_MEM_HIT",
	"TCP_DENIED",
	"TCP_DENIED_REPLY",
	"TCP_OFFLINE_HIT",
	"TCP_REDIRECT",
	"TCP_TUNNEL",
	"UDP_HIT",
	"UDP_MISS",
	"UDP_DENIED",
	"UDP_INVALID",
	"UDP_MISS_NOFETCH",
	"ICP_QUERY",
	"TYPE_MAX"
};
